apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: s19nvr7bo-nodejs 
  janus-idp.io/tekton: s19nvr7bo-nodejs
  backstage.io/kubernetes-id: s19nvr7bo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s19nvr7bo-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  